name: "Python, uv, and Just Setup"
description: "Sets up Python, installs uv & Just, caches and installs Python dependencies using uv."

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.11"
    type: string
  uv-cache-key-prefix: # Optional: allows customizing the cache key prefix if needed
    description: "Prefix for the uv cache key"
    required: false
    default: "uv-deps"
    type: string
  python-dependency-group: # Allows specifying which dependency groups to sync (comma-separated list)
    description: "Dependency groups to install with uv sync (e.g., dev, main). Multiple groups can be specified as a comma-separated list."
    required: false
    default: "dev"
    type: string
  python-extras: # Allows specifying which optional dependencies to install
    description: "Optional dependencies to install (e.g., plotting, docs). Multiple extras can be specified as a comma-separated list."
    required: false
    default: ""
    type: string

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Get uv cache directory
      id: uv-cache-dir # Give an ID to reference its output
      shell: bash
      run: echo "dir=$(uv cache dir)" >> $GITHUB_OUTPUT # uv must be on PATH here

    - name: Cache uv global dependencies
      uses: actions/cache@v4
      id: cache-uv-global
      with:
        path: ${{ steps.uv-cache-dir.outputs.dir }} # Path to uv's own global cache
        # A robust key includes the OS, Python version (if it affects venvs managed by uv), and lock/project files
        key: ${{ runner.os }}-${{ inputs.uv-cache-key-prefix }}-${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.uv-cache-key-prefix }}-${{ inputs.python-version }}-
          ${{ runner.os }}-${{ inputs.uv-cache-key-prefix }}-

    - name: Install Python dependencies with uv
      shell: bash
      run: |
        # Build the uv sync command arguments
        UV_SYNC_ARGS=()

        # Add dependency groups if specified
        DEPENDENCY_GROUPS="${{ inputs.python-dependency-group }}"
        if [ -n "$DEPENDENCY_GROUPS" ]; then
          IFS=',' read -ra GROUPS <<< "$DEPENDENCY_GROUPS"
          for group in "${GROUPS[@]}"; do
            group=$(echo "$group" | xargs)  # Trim whitespace
            if [ -n "$group" ]; then
              UV_SYNC_ARGS+=(--group "$group")
            fi
          done
        fi

        # Add optional dependencies (extras) if specified
        PYTHON_EXTRAS="${{ inputs.python-extras }}"
        if [ -n "$PYTHON_EXTRAS" ]; then
          IFS=',' read -ra EXTRAS <<< "$PYTHON_EXTRAS"
          for extra in "${EXTRAS[@]}"; do
            extra=$(echo "$extra" | xargs)  # Trim whitespace
            if [ -n "$extra" ]; then
              UV_SYNC_ARGS+=(--extra "$extra")
            fi
          done
        fi

        # Execute uv sync with the built arguments
        echo "Running uv sync with ${#UV_SYNC_ARGS[@]} additional arguments"
        if [ ${#UV_SYNC_ARGS[@]} -gt 0 ]; then
          echo "Arguments: ${UV_SYNC_ARGS[*]}"
        fi

        if [ ${#UV_SYNC_ARGS[@]} -eq 0 ]; then
          echo "Executing: uv sync"
          uv sync
        else
          echo "Executing: uv sync ${UV_SYNC_ARGS[*]}"
          uv sync "${UV_SYNC_ARGS[@]}"
        fi
        # If you use a uv.lock file and want to ensure it's strictly followed:
        # Add --frozen flag before uv sync
# No explicit outputs needed from this composite action for basic setup.
# If you needed to output something like the exact cache key used, you could define it:
# outputs:
#   uv-cache-hit:
#     description: 'Whether the uv cache was hit'
#     value: ${{ steps.cache-uv-global.outputs.cache-hit }}
