name: Check Commit

on:
  # enable all branches but main
  push:
    branches-ignore:
      - main
      - actions
  pull_request:
    branches: ["**"]

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python, uv, Just, and Dependencies
        uses: ./.github/actions/setup
        with:
          python-version: "3.11"

      - name: Run linters with Just
        run: just lint

  test:
    name: Run Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # test against multiple python versions
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}, uv, Just, and Dependencies
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests with Just and generate report
        run: just test-ci

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # Run this step even if tests fail, to report them
        with:
          name: Pytest Results (Python ${{ matrix.python-version }})
          path: "**/pytest-report.xml" # Path to your JUnit XML report file(s)
          reporter: java-junit # Reporter type for JUnit XML
          # Optional: Configure behavior for failures, e.g., fail the check if tests fail
          fail-on-error: "true"
