name: Bump version

on:
  push:
    branches:
      - main

jobs:
  ci-checks:
    name: Run CI Checks
    uses: ./.github/workflows/checks-reusable.yml

  bump-version:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    needs: [ci-checks]
    environment: pypi-release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create bump and changelog
        id: commitizen
        uses: commitizen-tools/commitizen-action@master
        with:
          changelog_increment_filename: body.md
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "body.md"
          tag_name: v${{ steps.commitizen.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python, uv, Just, and Dependencies
        uses: ./.github/actions/setup
        with:
          python-version: "3.11"

      - name: Publish to PyPI
        run: just publish-ci
