name: Bump version

on:
  workflow_run:
    workflows: ["check-commit.yml"]
    types:
      - completed
    branches: ["**"]

jobs:
  bump-version:
    # if: >
    #   github.event.workflow_run.conclusion == 'success' &&
    #   !startsWith(github.event.workflow_run.head_commit.message, 'bump:')
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Confirm Trigger and Print Workflow Information
        run: |
          echo "Minimal triggered job was executed successfully!"
          echo "This job was triggered by the completion of workflow: '${{ github.event.workflow_run.workflow.name }}'"
          echo "The triggering workflow ran on branch: '${{ github.event.workflow_run.head_branch }}'"
          echo "The triggering workflow ran for commit SHA: '${{ github.event.workflow_run.head_sha }}'"
          echo "Conclusion of the triggering workflow: '${{ github.event.workflow_run.conclusion }}'"
          echo "Commit message of the triggering commit: '${{ github.event.workflow_run.head_commit.message }}'"

      - name: Checkout the specific commit (preparation for future bumping logic)
        if: success() # Only checkout if the above conditions were met (job is running)
        uses: actions/checkout@v4
        with:
          # This checkouts out the code at the specific commit that completed the CI workflow
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0 # Important if/when you add Commitizen back, as it needs full history

      - name: Placeholder for Future Bumping Logic
        if: success()
        run: echo "Actual version bumping, changelog generation, and release creation logic would go here."
